### ISSUE TITLE
Really hope it can work with Biome's O Plenty or Wilder Wild.

### ISSUE THREAD

**Issue by SheanlR** [AnAwesomGuy/stone-shears#1]
I wanna use stone shear to cut the leaves in Biome's O Plenty and Wilder Wild, but the tool doesn't work. (∂дδ)

**Comment by AnAwesomGuy** [comment]
Once FabricMC#3493 gets merged this feature will become part of Fabric API itself, but I'll put a temporary fix for now.

**Comment by AnAwesomGuy** [comment]
@SheanlR fixed in bop side, closing

**Comment by SheanlR** [comment]
> @SheanlR fixed in bop side, closing

It works many thanX
